baseURL = "https://skylinemath.club/"
languageCode = "en-us"
title = "Skyline Math Club"
theme = "terminal"
paginate = 5

[params]
    contentTypeName = "posts"
    themeColor = "green"
    showMenuItems = 5
    showLanguageSelector = false
    fullWidthTheme = false
    centerTheme = false
    showFullContent = false

[markup.goldmark.renderer]
    unsafe = true

[blackfriday]
    fractions = false
    extensions = ["hardLineBreak"]

[languages]
    [languages.en]
        languageName = "English"
        title = "Skyline Math Club"
        keywords = ""
        copyright = ""

        [languages.en.params]
            [languages.en.params.logo]
                logoText = "Skyline Math Club"
                logoHomeLink = "/"
        
        [languages.en.menu]
            [[languages.en.menu.main]]
                identifier = "announcements"
                name = "Announcements"
                url = "/announcements"
            [[languages.en.menu.main]]
                identifier = "problem"
                name = "Problem of the Week"
                url = "/problem"
            [[languages.en.menu.main]]
                identifier = "roster"
                name = "Roster"
                url = "/roster"

